name: Data Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  data-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data quality checks
      run: |
        python -c "
        import pandas as pd
        df = pd.read_csv('data/Lead_Scoring.csv')
        assert df.shape[0] > 1000, 'Dataset muito pequeno'
        assert 'Converted' in df.columns, 'Coluna target não encontrada'
        assert df['Converted'].mean() > 0.1, 'Taxa de conversão muito baixa'
        print('✅ Todos os testes de qualidade passaram!')
        "
        
    - name: Run model training test
      run: |
        python src/lead_scoring_analysis.py
